# -*- mode: ruby -*-
# vi: set ft=ruby :

user = ENV['GUAVUSLABS_USER'] || ENV['USER']
node_name = "mesos-buildbox-#{user}.guavuslabs.local"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "CentOS-6.4-x86_64-Minimal"
  config.vm.box_url = "http://repo.guavuslabs.com/binaries/vagrantboxes/developer.nrel.gov/downloads/CentOS-6.4-x86_64-v20130427.box"

  config.vm.hostname = node_name

  config.vm.network :private_network, ip: "192.168.33.33"

  config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../rpms", "/mesos-rpms"

  config.vm.provider :virtualbox do |vb|
     # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "2024"]
  end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision :chef_solo do |chef|
  #   chef.cookbooks_path = "../chef/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  # end
  #
  # Requires:
  #  yum groupinstall 'Development Tools'
  #  yum install rpmdevtools
  #  installed rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
  #  yum install mock
  #  yum install atop
  #  yum install vim
  #  yum install snappy
  #  yum install gperftools-libs
  #  install jvm
  #
 
  config.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://chef-01.guavuslabs.com"
    #chef.node_name  = "developer"
    chef.validation_key_path = "#{ENV['HOME']}/.guavuslabs-developer/chef-01/chef-validator.pem"
    chef.validation_client_name = "chef-validator"

    # Change the node/client name for the Chef Server
    chef.node_name = node_name

    chef.add_role "mesos-buildbox-local"
  end

end
